steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/hello-app-366807/cnic', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/hello-app-366807/cnic']